server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
  mapper-locations: classpath:com/atguigu/auth/mapper/xml/*.xml

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guigu-oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: bestsdeever

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-4
#  redis:
#    host: localhost #192.168.68.134
#    port: 6379
#    database: 0
#    timeout: 1800000
#    password: 21xnDHGeLWfcN6eFvRBqfsJHyJDAcRsg
#    jedis:
#      pool:
#        max-active: 20 #最大连接数
#        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
#        max-idle: 5    #最大空闲
#        min-idle: 0     #最小空闲